### ISSUE TITLE
Is it possible to use this library with node?

### ISSUE THREAD

**Issue by cromega** [karak/riot-test-renderer#25]
I'm trying to use this library to test components with Jasmine but I'm not quite sure if it's supposed to work like that.

I have a simple test like this:

```js
var mount = require('riot-test-utils').mount;
var fs = require('fs');

describe("Job", function() {
  it("displays job name", function() {
    var src = fs.readFileSync('src/tags/job/job.tag').toString();
    tag = mount(src, { status: 'success' });
    expect(tag.html()).toBe("foo");
  });
});

```

I get the following error:

```
./node_modules/simulate-event/simulate-event.js:269
  UIEvent: window.UIEvent,

ReferenceError: window is not defined


[...]

    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (./node_modules/riot-test-utils/dist/index.js:1:233)
```

**Comment by cromega** [comment]
Right, I was supposed to set up jsdom. It would be nice if these things were documented with a few examples though.

**Comment by karak** [comment]
Isn't this enough? <https://www.npmjs.com/package/riot-test-utils#requirement>

**Comment by cromega** [comment]
@karak for someone who is familiar with how things in js world generally work, I'm sure it is. For me it wasn't quite that obvious.
